- link:
    ~/.gitconfig:
        path:   tools/vcs/git/gitconfig
        relink: true
        create: true
        force:  true
    ~/.gitignore_global:
        path:   tools/vcs/git/gitignore_global
        relink: true
        create: true
        force:  true
