#!/bin/bash

# Variables
DOT_LOC="${HOME}/dotfiles"
FISH_LOC="${DOT_LOC}/shells/fish"
FISHER_LOC="${FISH_LOC}/fisherman"
PLUGIN_FILE="${FISH_LOC}/plugins"

# Initialize the list of plugins
to_install=""

cd ${FISHER_LOC}

# Read the lines of plugin, for the plugins not found in fisherman, add them to the install cmd
while read plugin; do
  if [[ ! -d "${FISHER_LOC}/${plugin}/" ]]; then
     to_install+=" ${plugin}"
  fi
done <${PLUGIN_FILE}

echo "The following plugins were missing:${to_install}"
fish -c "fisher install${to_install}"
